<?php
// /tools/html-table-generator/index.php

// ==== Dynamic Variables (edit these per tool) ====
$tool_name     = "HTML Table Generator"; 
$tool_details  = "Create responsive, customizable HTML tables instantly with our free online HTML Table Generator. No coding required - design professional tables with custom styling, borders, colors, and padding.";
$why_use_text  = "Creating HTML tables manually can be time-consuming and error-prone, especially when dealing with complex styling and multiple rows and columns. Our HTML Table Generator simplifies this process by providing an intuitive visual interface where you can design your table exactly how you want it.\n\nWith real-time preview and instant code generation, you can see your changes immediately and copy clean, semantic HTML code ready to use in your website or application. Whether you're a web developer, content creator, or student learning HTML, this tool saves you valuable time and ensures your tables are properly structured.\n\nThe generator supports all essential table features including custom colors, padding, borders, text alignment, and responsive design options. You can create everything from simple data tables to complex styled tables without writing a single line of code manually.";
$how_to_use    = [
  "Set the number of columns and rows you need for your table using the input fields at the top of the generator.",
  "Click on any cell in the table preview to enter your data. You can add headers, text, numbers, or any content you need.",
  "Customize your table styling using the options panel - choose colors for headers and body, adjust padding, set border styles, and configure text alignment.",
  "Enable or disable features like border-collapse, adjust border width and color, and set width/height percentages for responsive design.",
  "Once satisfied with your design, click the copy button next to the HTML code to copy it to your clipboard, then paste it directly into your HTML file or CMS."
];

// ==== FAQ Placeholder (Template Guideline) ====
$faqs = [
  [
    "What is an HTML table and why do I need a generator for it?", 
    "An HTML table is a structured way to display data in rows and columns on a web page using HTML markup. Tables are essential for presenting information like pricing comparisons, schedules, data reports, and any content that benefits from a grid layout. <br><br>While you can write HTML table code manually, using a generator saves significant time and reduces errors. Our HTML Table Generator provides a visual interface where you can see your table as you build it, automatically generates clean, valid HTML code, and handles all the complex styling attributes. This is especially helpful when creating tables with custom colors, borders, and responsive design features that would require writing many lines of CSS code manually."
  ],
  [
    "Can I customize the colors and styling of my HTML table?", 
    "Absolutely! Our HTML Table Generator offers comprehensive styling options. You can customize header background colors, body background colors, font colors for both headers and body text, border colors, and styles. <br><br>The tool also allows you to adjust padding for better spacing, set border width and style (solid, dashed, dotted), choose text alignment (left, center, right), and configure width and height as percentages for responsive design. All these customizations are applied in real-time, so you can see exactly how your table will look before copying the code. The generated HTML includes inline styles, making it easy to use the table anywhere without needing separate CSS files."
  ],
  [
    "Is the generated HTML table code responsive and mobile-friendly?", 
    "Yes, the HTML tables generated by our tool can be made responsive. When you set the table width using percentage values (like 100%) instead of fixed pixels, the table will automatically adjust to fit different screen sizes. <br><br>The generated code uses semantic HTML5 table elements (table, thead, tbody, tr, th, td) which are recognized by all modern browsers and screen readers. For better mobile responsiveness, you can adjust the width percentage and padding values. The tool generates clean, lightweight code that loads quickly on all devices. If you need advanced responsive features like horizontal scrolling on mobile or stacked columns, you can easily add those with additional CSS after generating the base table code."
  ],
  [
    "How do I add or edit content in the table cells?", 
    "Adding and editing content in your table is simple and intuitive. Once you've set the number of rows and columns, a preview table appears on the screen. Simply click on any cell (header or body) to select it and start typing your content. <br><br>You can enter any text, numbers, or even HTML entities in the cells. The preview updates in real-time as you type, and all your content is automatically included in the generated HTML code. If you need to change the content later, just click on the cell again and modify the text. There's no limit to how much text you can add per cell, though for best visual results, consider your table's width and padding settings when adding longer content."
  ],
  [
    "Can I use border-collapse and what does it do?", 
    "Border-collapse is a CSS property that controls how table borders are displayed, and yes, our generator fully supports it. When border-collapse is enabled (set to 'collapse'), the borders of adjacent cells merge into a single border, creating a cleaner, more compact look. This is the most common style for data tables. <br><br>When border-collapse is disabled (set to 'separate'), each cell has its own distinct border, creating visible spacing between cells. Our generator includes a checkbox to toggle this feature, and you can preview the effect immediately. The border-collapse property is particularly important when you're using border spacing or want a specific visual style. Most professional data tables use collapsed borders for a clean, modern appearance."
  ],
  [
    "What file format is the output and how do I use it in my website?", 
    "The HTML Table Generator outputs pure HTML code that you can directly copy and paste into your website. The code is provided in a text format that includes both the HTML structure and inline CSS styling. <br><br>To use it on your website, simply click the copy button, then paste the code into your HTML file wherever you want the table to appear. If you're using a Content Management System (CMS) like WordPress, Wix, or Squarespace, switch to the HTML or code editor view and paste the code there. The generated code is self-contained with inline styles, so you don't need to add separate CSS files. However, you can also extract the styles and add them to your external stylesheet if you prefer. The code is compatible with all modern browsers and follows HTML5 standards."
  ],
  [
    "Does this tool require any installation or registration?", 
    "No installation or registration is required whatsoever. Our HTML Table Generator is a completely free, web-based tool that runs directly in your browser. You don't need to download any software, create an account, or provide any personal information. <br><br>Simply visit the page, start designing your table, and copy the generated code. All processing happens on your device in real-time, which means your data remains private and the tool works even without a constant internet connection once the page is loaded. There are no limits on how many tables you can create or how often you can use the tool. It's designed to be accessible and easy to use for everyone, from beginners learning HTML to professional developers who need to quickly generate table code."
  ],
  [
    "Can I preview how my table will look before copying the code?", 
    "Yes! Real-time preview is one of the core features of our HTML Table Generator. As you make any changes - whether adding content, adjusting colors, modifying borders, or changing padding - you'll see the table update instantly in the preview section. <br><br>This live preview shows you exactly how your table will appear on your website, making it easy to experiment with different styles and configurations until you achieve the perfect look. The preview uses the same rendering as modern web browsers, so what you see in the generator is what you'll get on your website. This eliminates the need for trial and error when coding tables manually and ensures you're satisfied with the design before implementing it on your live site."
  ]
];

$page_title = $tool_name;

// ==== Auto Fetch Domain ====
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? "https://" : "http://";
$domain   = $_SERVER['HTTP_HOST'];

// ==== Image Fallback ====
$tool_slug  = strtolower(str_replace(' ', '-', $tool_name));
$tool_image = "/assets/images/{$tool_slug}.png";
if (!file_exists($_SERVER['DOCUMENT_ROOT'] . $tool_image)) {
    $tool_image = "/assets/images/default.png";
}

// ==== SEO Meta Tags ====
$meta_title = $tool_name . " | TG Data Hub Tools";
$meta_desc  = $tool_details . " Use this free tool to simplify your work online. Easy to use, fast and secure.";
$canonical  = $protocol . $domain . "/tools/" . $tool_slug;

require dirname(__DIR__, 2).'/partials/header.php';
?>

<!-- ==== SEO HEAD Extra ==== -->
<meta name="description" content="<?= htmlspecialchars($meta_desc) ?>">
<link rel="canonical" href="<?= $canonical ?>">

<!-- Open Graph -->
<meta property="og:title" content="<?= htmlspecialchars($meta_title) ?>">
<meta property="og:description" content="<?= htmlspecialchars($meta_desc) ?>">
<meta property="og:type" content="website">
<meta property="og:url" content="<?= $canonical ?>">
<meta property="og:image" content="<?= $protocol . $domain . $tool_image ?>">

<!-- Twitter Card -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="<?= htmlspecialchars($meta_title) ?>">
<meta name="twitter:description" content="<?= htmlspecialchars($meta_desc) ?>">
<meta name="twitter:image" content="<?= $protocol . $domain . $tool_image ?>">

<main class="max-w-5xl mx-auto px-4 py-8">
  <!-- Breadcrumbs -->
  <nav aria-label="Breadcrumb" class="mb-4 text-sm text-slate-500">
    <ol class="list-reset flex space-x-2">
      <li><a href="/" class="hover:underline">Home</a></li>
      <li>/</li>
      <li><a href="/tools" class="hover:underline">Tools</a></li>
      <li>/</li>
      <li class="text-slate-700"><?= htmlspecialchars($tool_name) ?></li>
    </ol>
  </nav>

  <!-- Main Card -->
  <section class="bg-white rounded-2xl border border-slate-200 shadow-lg p-6 md:p-8">

    <!-- Title -->
    <header class="mb-6 text-center">
      <h1 class="text-2xl md:text-3xl font-extrabold tracking-tight text-slate-800">
        <?= htmlspecialchars($tool_name) ?>
      </h1>
      <p class="mt-2 text-slate-600"><?= $tool_details ?></p>
    </header>

    <!-- Tool Start -->
    <div class="space-y-6">
      <!-- Controls Panel -->
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4 p-4 bg-slate-50 rounded-lg border border-slate-200">
        <!-- Columns & Rows -->
        <div>
          <label class="block text-sm font-semibold text-slate-700 mb-2">
            <svg class="inline w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 5a1 1 0 011-1h4a1 1 0 011 1v4a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM14 5a1 1 0 011-1h4a1 1 0 011 1v4a1 1 0 01-1 1h-4a1 1 0 01-1-1V5zM4 15a1 1 0 011-1h4a1 1 0 011 1v4a1 1 0 01-1 1H5a1 1 0 01-1-1v-4zM14 15a1 1 0 011-1h4a1 1 0 011 1v4a1 1 0 01-1 1h-4a1 1 0 01-1-1v-4z"/>
            </svg>
            Columns
          </label>
          <input type="number" id="numCols" value="4" min="1" max="20" 
                 class="w-full px-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
        </div>
        
        <div>
          <label class="block text-sm font-semibold text-slate-700 mb-2">
            <svg class="inline w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
            </svg>
            Rows
          </label>
          <input type="number" id="numRows" value="4" min="1" max="50" 
                 class="w-full px-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
        </div>

        <!-- Text Align -->
        <div>
          <label class="block text-sm font-semibold text-slate-700 mb-2">
            <svg class="inline w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7"/>
            </svg>
            Text Align
          </label>
          <select id="textAlign" class="w-full px-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
            <option value="left">Left</option>
            <option value="center" selected>Center</option>
            <option value="right">Right</option>
          </select>
        </div>

        <!-- Padding -->
        <div>
          <label class="block text-sm font-semibold text-slate-700 mb-2">
            <svg class="inline w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"/>
            </svg>
            Padding (px)
          </label>
          <input type="number" id="cellPadding" value="12" min="0" max="50" 
                 class="w-full px-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
        </div>

        <!-- Width -->
        <div>
          <label class="block text-sm font-semibold text-slate-700 mb-2">
            <svg class="inline w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16V4m0 0L3 8m4-4l4 4m6 0v12m0 0l4-4m-4 4l-4-4"/>
            </svg>
            Width (%)
          </label>
          <input type="number" id="tableWidth" value="100" min="10" max="100" 
                 class="w-full px-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
        </div>

        <!-- Border Width -->
        <div>
          <label class="block text-sm font-semibold text-slate-700 mb-2">
            <svg class="inline w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17V7m0 10a2 2 0 01-2 2H5a2 2 0 01-2-2V7a2 2 0 012-2h2a2 2 0 012 2m0 10a2 2 0 002 2h2a2 2 0 002-2M9 7a2 2 0 012-2h2a2 2 0 012 2m0 10V7"/>
            </svg>
            Border Width (px)
          </label>
          <input type="number" id="borderWidth" value="1" min="0" max="10" 
                 class="w-full px-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
        </div>
      </div>

      <!-- Color & Style Controls -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4 p-4 bg-indigo-50 rounded-lg border border-indigo-200">
        <!-- Header BG Color -->
        <div>
          <label class="block text-sm font-semibold text-slate-700 mb-2">Header BG Color</label>
          <input type="color" id="headerBgColor" value="#4f46e5" 
                 class="w-full h-10 rounded border border-slate-300">
        </div>

        <!-- Header Text Color -->
        <div>
          <label class="block text-sm font-semibold text-slate-700 mb-2">Header Text Color</label>
          <input type="color" id="headerTextColor" value="#ffffff" 
                 class="w-full h-10 rounded border border-slate-300">
        </div>

        <!-- Body BG Color -->
        <div>
          <label class="block text-sm font-semibold text-slate-700 mb-2">Body BG Color</label>
          <input type="color" id="bodyBgColor" value="#ffffff" 
                 class="w-full h-10 rounded border border-slate-300">
        </div>

        <!-- Body Text Color -->
        <div>
          <label class="block text-sm font-semibold text-slate-700 mb-2">Body Text Color</label>
          <input type="color" id="bodyTextColor" value="#475569" 
                 class="w-full h-10 rounded border border-slate-300">
        </div>

        <!-- Border Color -->
        <div>
          <label class="block text-sm font-semibold text-slate-700 mb-2">Border Color</label>
          <input type="color" id="borderColor" value="#e5e7eb" 
                 class="w-full h-10 rounded border border-slate-300">
        </div>

        <!-- Border Style -->
        <div>
          <label class="block text-sm font-semibold text-slate-700 mb-2">Border Style</label>
          <select id="borderStyle" class="w-full px-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
            <option value="solid">Solid</option>
            <option value="dashed">Dashed</option>
            <option value="dotted">Dotted</option>
            <option value="double">Double</option>
          </select>
        </div>
      </div>

      <!-- Checkboxes -->
      <div class="flex flex-wrap gap-4 p-4 bg-slate-50 rounded-lg border border-slate-200">
        <label class="flex items-center space-x-2 cursor-pointer">
          <input type="checkbox" id="borderCollapse" checked class="w-4 h-4 text-indigo-600 border-slate-300 rounded focus:ring-indigo-500">
          <span class="text-sm font-medium text-slate-700">Border Collapse</span>
        </label>
        
        <label class="flex items-center space-x-2 cursor-pointer">
          <input type="checkbox" id="stripedRows" class="w-4 h-4 text-indigo-600 border-slate-300 rounded focus:ring-indigo-500">
          <span class="text-sm font-medium text-slate-700">Striped Rows</span>
        </label>

        <label class="flex items-center space-x-2 cursor-pointer">
          <input type="checkbox" id="hoverEffect" class="w-4 h-4 text-indigo-600 border-slate-300 rounded focus:ring-indigo-500">
          <span class="text-sm font-medium text-slate-700">Hover Effect</span>
        </label>
      </div>

      <!-- Table Preview -->
      <div>
        <h3 class="text-lg font-bold text-slate-800 mb-3 flex items-center">
          <svg class="w-5 h-5 mr-2 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/>
          </svg>
          Table Preview
        </h3>
        <div class="overflow-x-auto border border-slate-300 rounded-lg p-4 bg-white">
          <div id="tablePreview"></div>
        </div>
        <p class="text-xs text-slate-500 mt-2">Click on any cell and type to edit content directly</p>
      </div>

      <!-- HTML Code Output -->
      <div>
        <div class="flex items-center justify-between mb-3">
          <h3 class="text-lg font-bold text-slate-800 flex items-center">
            <svg class="w-5 h-5 mr-2 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"/>
            </svg>
            HTML Code
          </h3>
          <button id="copyBtn" class="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition flex items-center space-x-2 focus:ring-2 focus:ring-indigo-500">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"/>
            </svg>
            <span>Copy Code</span>
          </button>
        </div>
        <div class="relative">
          <pre id="htmlCode" class="bg-slate-800 text-slate-100 p-4 rounded-lg overflow-x-auto text-sm"><code></code></pre>
          <div id="copyNotification" class="hidden absolute top-2 right-2 bg-green-500 text-white px-3 py-1 rounded text-sm">Copied!</div>
        </div>
      </div>
    </div>

    <script>
      // Table data storage
      let tableData = {
        headers: [],
        rows: []
      };

      // Initialize
      function initTable() {
        const cols = parseInt(document.getElementById('numCols').value);
        const rows = parseInt(document.getElementById('numRows').value);
        
        tableData.headers = Array(cols).fill('').map((_, i) => `Header ${i + 1}`);
        tableData.rows = Array(rows).fill(null).map((_, i) => 
          Array(cols).fill('').map((_, j) => `Cell ${i + 1}-${j + 1}`)
        );
        
        updateTable();
      }

      // Update table preview and code
      function updateTable() {
        const cols = parseInt(document.getElementById('numCols').value);
        const rows = parseInt(document.getElementById('numRows').value);
        const textAlign = document.getElementById('textAlign').value;
        const padding = document.getElementById('cellPadding').value;
        const tableWidth = document.getElementById('tableWidth').value;
        const borderWidth = document.getElementById('borderWidth').value;
        const borderStyle = document.getElementById('borderStyle').value;
        const borderCollapse = document.getElementById('borderCollapse').checked;
        const stripedRows = document.getElementById('stripedRows').checked;
        const hoverEffect = document.getElementById('hoverEffect').checked;
        
        const headerBgColor = document.getElementById('headerBgColor').value;
        const headerTextColor = document.getElementById('headerTextColor').value;
        const bodyBgColor = document.getElementById('bodyBgColor').value;
        const bodyTextColor = document.getElementById('bodyTextColor').value;
        const borderColor = document.getElementById('borderColor').value;

        // Adjust data arrays if dimensions changed
        if (tableData.headers.length !== cols) {
          if (cols > tableData.headers.length) {
            const diff = cols - tableData.headers.length;
            tableData.headers.push(...Array(diff).fill('').map((_, i) => `Header ${tableData.headers.length + i + 1}`));
            tableData.rows.forEach(row => {
              row.push(...Array(diff).fill(''));
            });
          } else {
            tableData.headers = tableData.headers.slice(0, cols);
            tableData.rows.forEach(row => row.length = cols);
          }
        }

        if (tableData.rows.length !== rows) {
          if (rows > tableData.rows.length) {
            const diff = rows - tableData.rows.length;
            for (let i = 0; i < diff; i++) {
              tableData.rows.push(Array(cols).fill(''));
            }
          } else {
            tableData.rows = tableData.rows.slice(0, rows);
          }
        }

        // Generate table HTML
        let tableStyle = `width: ${tableWidth}%; border-collapse: ${borderCollapse ? 'collapse' : 'separate'}; border: ${borderWidth}px ${borderStyle} ${borderColor};`;
        let html = `<table style="${tableStyle}">\n  <thead>\n    <tr>`;
        
        tableData.headers.forEach((header, i) => {
          const headerStyle = `background-color: ${headerBgColor}; color: ${headerTextColor}; padding: ${padding}px; border: ${borderWidth}px ${borderStyle} ${borderColor}; text-align: ${textAlign}; cursor: text;`;
          html += `\n      <th contenteditable="true" data-type="header" data-index="${i}" style="${headerStyle}">${header || ''}</th>`;
        });
        
        html += '\n    </tr>\n  </thead>\n  <tbody>';
        
        tableData.rows.forEach((row, rowIndex) => {
          html += '\n    <tr>';
          row.forEach((cell, colIndex) => {
            let cellStyle = `padding: ${padding}px; border: ${borderWidth}px ${borderStyle} ${borderColor}; text-align: ${textAlign}; color: ${bodyTextColor}; cursor: text;`;
            
            if (stripedRows && rowIndex % 2 === 1) {
              cellStyle += ` background-color: #f8fafc;`;
            } else {
              cellStyle += ` background-color: ${bodyBgColor};`;
            }
            
            html += `\n      <td contenteditable="true" data-type="body" data-row="${rowIndex}" data-col="${colIndex}" style="${cellStyle}">${cell || ''}</td>`;
          });
          html += '\n    </tr>';
        });
        
        html += '\n  </tbody>\n</table>';

        // Add hover effect CSS if enabled
        if (hoverEffect) {
          html = `<style>\ntable tr:hover td { background-color: #e0e7ff !important; }\n</style>\n` + html;
        }

        // Update preview
        document.getElementById('tablePreview').innerHTML = html;
        
        // Add event listeners for inline editing
        addCellEditListeners();
        
        // Update code display (without contenteditable attributes)
        const cleanHtml = html.replace(/\scontenteditable="true"/g, '')
                             .replace(/\sdata-type="[^"]+"/g, '')
                             .replace(/\sdata-index="[^"]+"/g, '')
                             .replace(/\sdata-row="[^"]+"/g, '')
                             .replace(/\sdata-col="[^"]+"/g, '')
                             .replace(/cursor: text;/g, '');
        document.getElementById('htmlCode').textContent = cleanHtml;
      }

      // Add event listeners for inline cell editing
      function addCellEditListeners() {
        const cells = document.querySelectorAll('#tablePreview [contenteditable="true"]');
        
        cells.forEach(cell => {
          // Update data on blur (when user clicks outside)
          cell.addEventListener('blur', function() {
            const type = this.getAttribute('data-type');
            const content = this.textContent.trim();
            
            if (type === 'header') {
              const index = parseInt(this.getAttribute('data-index'));
              tableData.headers[index] = content;
            } else {
              const row = parseInt(this.getAttribute('data-row'));
              const col = parseInt(this.getAttribute('data-col'));
              tableData.rows[row][col] = content;
            }
            
            // Update only the code, not the preview to avoid losing focus
            updateCodeOnly();
          });

          // Handle Enter key to move to next cell
          cell.addEventListener('keydown', function(e) {
            if (e.key === 'Enter' && !e.shiftKey) {
              e.preventDefault();
              this.blur();
            }
          });
        });
      }

      // Update only the HTML code display without refreshing preview
      function updateCodeOnly() {
        const cols = parseInt(document.getElementById('numCols').value);
        const rows = parseInt(document.getElementById('numRows').value);
        const textAlign = document.getElementById('textAlign').value;
        const padding = document.getElementById('cellPadding').value;
        const tableWidth = document.getElementById('tableWidth').value;
        const borderWidth = document.getElementById('borderWidth').value;
        const borderStyle = document.getElementById('borderStyle').value;
        const borderCollapse = document.getElementById('borderCollapse').checked;
        const stripedRows = document.getElementById('stripedRows').checked;
        const hoverEffect = document.getElementById('hoverEffect').checked;
        
        const headerBgColor = document.getElementById('headerBgColor').value;
        const headerTextColor = document.getElementById('headerTextColor').value;
        const bodyBgColor = document.getElementById('bodyBgColor').value;
        const bodyTextColor = document.getElementById('bodyTextColor').value;
        const borderColor = document.getElementById('borderColor').value;

        let tableStyle = `width: ${tableWidth}%; border-collapse: ${borderCollapse ? 'collapse' : 'separate'}; border: ${borderWidth}px ${borderStyle} ${borderColor};`;
        let html = `<table style="${tableStyle}">\n  <thead>\n    <tr>`;
        
        tableData.headers.forEach(header => {
          const headerStyle = `background-color: ${headerBgColor}; color: ${headerTextColor}; padding: ${padding}px; border: ${borderWidth}px ${borderStyle} ${borderColor}; text-align: ${textAlign};`;
          html += `\n      <th style="${headerStyle}">${header || '&nbsp;'}</th>`;
        });
        
        html += '\n    </tr>\n  </thead>\n  <tbody>';
        
        tableData.rows.forEach((row, rowIndex) => {
          html += '\n    <tr>';
          row.forEach(cell => {
            let cellStyle = `padding: ${padding}px; border: ${borderWidth}px ${borderStyle} ${borderColor}; text-align: ${textAlign}; color: ${bodyTextColor};`;
            
            if (stripedRows && rowIndex % 2 === 1) {
              cellStyle += ` background-color: #f8fafc;`;
            } else {
              cellStyle += ` background-color: ${bodyBgColor};`;
            }
            
            html += `\n      <td style="${cellStyle}">${cell || '&nbsp;'}</td>`;
          });
          html += '\n    </tr>';
        });
        
        html += '\n  </tbody>\n</table>';

        if (hoverEffect) {
          html = `<style>\ntable tr:hover td { background-color: #e0e7ff !important; }\n</style>\n` + html;
        }

        document.getElementById('htmlCode').textContent = html;
      }

      // Copy to clipboard
      document.getElementById('copyBtn').addEventListener('click', function() {
        const code = document.getElementById('htmlCode').textContent;
        navigator.clipboard.writeText(code).then(() => {
          const notification = document.getElementById('copyNotification');
          notification.classList.remove('hidden');
          setTimeout(() => notification.classList.add('hidden'), 2000);
        });
      });

      // Event listeners
      document.getElementById('numCols').addEventListener('change', updateTable);
      document.getElementById('numRows').addEventListener('change', updateTable);
      document.getElementById('textAlign').addEventListener('change', updateTable);
      document.getElementById('cellPadding').addEventListener('input', updateTable);
      document.getElementById('tableWidth').addEventListener('input', updateTable);
      document.getElementById('borderWidth').addEventListener('input', updateTable);
      document.getElementById('borderStyle').addEventListener('change', updateTable);
      document.getElementById('borderCollapse').addEventListener('change', updateTable);
      document.getElementById('stripedRows').addEventListener('change', updateTable);
      document.getElementById('hoverEffect').addEventListener('change', updateTable);
      document.getElementById('headerBgColor').addEventListener('input', updateTable);
      document.getElementById('headerTextColor').addEventListener('input', updateTable);
      document.getElementById('bodyBgColor').addEventListener('input', updateTable);
      document.getElementById('bodyTextColor').addEventListener('input', updateTable);
      document.getElementById('borderColor').addEventListener('input', updateTable);

      // Initialize on load
      initTable();
    </script>
    <!-- Tool End -->

    <!-- Why use -->
    <div class="mt-8">
      <h2 class="text-xl font-bold text-slate-800 mb-2">Why use <?= htmlspecialchars($tool_name) ?>?</h2>
      <?php foreach (explode("\n\n", $why_use_text) as $paragraph): ?>
        <p class="text-slate-600 leading-relaxed mb-3"><?= nl2br(htmlspecialchars(trim($paragraph))) ?></p>
      <?php endforeach; ?>
    </div>

    <!-- How to use -->
    <div class="mt-6">
      <h2 class="text-xl font-bold text-slate-800 mb-2">How to use <?= htmlspecialchars($tool_name) ?></h2>
      <ol class="list-decimal pl-5 space-y-2 text-slate-600">
        <?php foreach ($how_to_use as $step): ?>
          <li><?= htmlspecialchars($step) ?></li>
        <?php endforeach; ?>
      </ol>
    </div>

    <!-- FAQ -->
    <div class="mt-6 border-t border-slate-200 pt-4" id="faq">
      <h2 class="text-xl font-bold text-slate-800 mb-3"><?= htmlspecialchars($tool_name) ?> – FAQ</h2>
      <div class="space-y-3">
        <?php foreach ($faqs as [$q, $a]): ?>
          <details class="group border border-slate-200 rounded-lg p-3">
            <summary class="cursor-pointer font-semibold flex items-center justify-between" aria-expanded="false">
              <?= htmlspecialchars($q) ?>
              <span class="text-slate-400 group-open:rotate-45 transition">+</span>
            </summary>
            <div class="mt-2 text-slate-600 leading-relaxed">
              <?= nl2br(htmlspecialchars_decode($a)) ?>
            </div>
          </details>
        <?php endforeach; ?>
      </div>
    </div>

    <!-- Bottom CTA -->
    <?php require dirname(__DIR__, 2).'/partials/back-to-tools.php'; ?>
  </section>
</main>

<?php require dirname(__DIR__, 2).'/partials/footer.php'; ?>

<!-- FAQ Schema -->
<script type="application/ld+json">
<?= json_encode([
  "@context" => "https://schema.org",
  "@type" => "FAQPage",
  "mainEntity" => array_map(function($faq) {
      return [
        "@type" => "Question",
        "name" => $faq[0],
        "acceptedAnswer" => [
          "@type" => "Answer",
          "text" => $faq[1]
        ]
      ];
  }, $faqs)
], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT); ?>
</script>

<!-- WebPage Schema -->
<script type="application/ld+json">
<?= json_encode([
  "@context" => "https://schema.org",
  "@type" => "WebPage",
  "name" => $meta_title,
  "description" => $meta_desc,
  "url" => $canonical
], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT); ?>
</script>
